# Generated by Django 4.1.2 on 2022-10-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realtor", old_name="decription", new_name="description",
        ),
    ]
